### ISSUE TITLE
Support multiple preview images on attachments?

### ISSUE THREAD

**Issue by pysailor** [ploneintranet/ploneintranet#130]
In the activity stream, if you select a file for attaching to a post, you see mutliple thumbnail images in the posting field. However once the post is submitted, only one image is displayed.
@cornae It is probably intentional that the proto only supports one preview image per attachment? I'm asking because technically it would be possible for us to also show multiple images there, if the attachment is more than 1 page long.
Messing directly in the HTML to add a second image does not instantly look nice - here's a comparison screen-shot of the thumbnails while writing a post, and my tampered post with 2 images.
![screen shot 2015-03-29 at 09 39 28](https://cloud.githubusercontent.com/assets/642660/6884556/423316e2-d5f8-11e4-86de-1aa80e0d6902.png)

**Comment by gyst** [comment]
Looks like a bug to me. The actual rendering should behave the same as the sneak preview before submitting the post.

**Comment by cornae** [comment]
It's intentional to have only one image in the big version. If you click it and you go to the the document, if it is a document that lives in a Workspace or something, you'll see all the pages. In this case it might be a post directly to timeline and then you should be able to go to some expanded version of the post, which is not foreseen. Showing more than a few images together would make the post far too long, that's why it's capped on 2 images. A rather cheap solution would be to put pat-gallery on a group of anchors with links to the full res versions of all pages and put an attribute hidden on each anchor except the first. I would design some sort of indication on the first image that there are more pages to be shown.

**Comment by gyst** [comment]
Resolved above.
