### ISSUE TITLE
Retro: ploneintranet api

### ISSUE THREAD

**Issue by jaroel** [ploneintranet/ploneintranet#172]

**Comment by gyst** [comment]
Should it be ploneintranet.(???).api or ploneintranet.api.(???)
a) ploneintranet.microblog.api, ploneintranet.network.api
b) ploneintranet.api.microblog, ploneintranet.api.network

My vote is for b) because:
1. It offers better discoverability. The whole API is in ploneintranet.api
2. It can be reorganized in a way that matches API usage, instead of being tightly coupled to the implementation package layout.

**Comment by pbauer** [comment]
+1 for b)

**Comment by wengole** [comment]
:+1: b)

**Comment by ale-rt** [comment]
I am also for b)
You want to have:
- from ploneintranet import api

**Comment by mattss** [comment]
I'm going to have a stab at this, as we need it for profiles stuff. Will start by moving @pbauer's messaging stuff into ploneintranet.api

**Comment by mattss** [comment]
ploneintranet.api is alive! Also build sphinx api-docs into our doc setup, so we get this: http://docs.ploneintranet.org/development/components/ploneintranet-api.html
