### ISSUE TITLE
Cannot create a user to login

### ISSUE THREAD

**Issue by maartenkling** [ploneintranet/ploneintranet#393]
there is no way to create a user for the intranet

**Comment by pilz** [comment]
For now you can use /profiles/@@import-users and upload a csv file with the available fields mentioned on that page.

**Comment by maartenkling** [comment]
there is no /profiles/ folder

**Comment by pilz** [comment]
Ah, so the issues might be that we only create it with the test content. That needs to go into the main setuphandlers then.

**Comment by pilz** [comment]
Task: Make sure there is a profiles folder from the start.

**Comment by gyst** [comment]
Possibly duplicates #420. Scope is only to make sure there is a /profiles/ folder and it's accessible

**Comment by gyst** [comment]
Profiles folder fixed in #420.
Todo: add documentation about usermanagement in docs.
See http://localhost:8080/Plone/profiles/@@import-users
Please also mention #394 in the docs - one should not do any zope admin work _except_ this @@import-users stuff - make sure to use that channel to create a user with Manager (dev) and one with Site Administrator (client) and these should NOT be named "admin" (because that would overlay the Zope user with a Plone membrane user causing weird problems).

**Comment by gyst** [comment]
@ale-rt no reason for you to take this on, will assign to somebody else

**Comment by gyst** [comment]
Fixed in #789
