### ISSUE TITLE
Userprofile without image should fall back to default avatar

### ISSUE THREAD

**Issue by maartenkling** [ploneintranet/ploneintranet#403]
<img width="318" alt="screen shot 2015-07-08 at 15 32 12" src="https://cloud.githubusercontent.com/assets/946684/8571367/975a0648-2586-11e5-9f7a-866f3726cdbe.png">

**Comment by pilz** [comment]
We must implement a placeholder image for users without profile image.

**Comment by gyst** [comment]
In #580 @cornae said: "An avatar image is broken. When there is no avatar available, it should default to the default user image that is available in the media folder." -> I don't find the default image.

That the admin avatar doesn't render is because there is no admin user, different bug #596 #394.

For this bug: userprofile.browser.userprofile.stream_avatar_data() does not provide a check and fallback for a missing avatar image. TODO.

**Comment by pilz** [comment]
we have prototype/media/defaultUser-186.png and defaultUser.png

**Comment by pilz** [comment]
This is fixed. There is still an issue in the stream if you post as admin, but we declared that as invalid and non supported. You must use a user with a profile.
