### ISSUE TITLE
http://localhost:8080/Plone/@@personal-preferences unstyled

### ISSUE THREAD

**Issue by maartenkling** [ploneintranet/ploneintranet#410]
as a user i can reach this page so it needs to be styled or removed

**Comment by gyst** [comment]
Link should be hidden or link to editable userprofile

**Comment by allcaps** [comment]
The view should be blocked. @@personal-preferences should give 404.

**Comment by gyst** [comment]
Better is to redirect to your actual user profile, like @@author does.

**Comment by gyst** [comment]
The view now returns a 404 as per #513. 
Todo:
- add 'Personal profile' action pointing to actual user profile as per prototype
- do not add 'Personal settings' since we don't have that implemented yet
- add logout actions

The markup should implement exactly the prototype so it looks like the prototype, see below.
This may require some diazo tweaking in ploneintranet.theme after setting up the portal actions in ploneintranet.suite

![actions](https://cloud.githubusercontent.com/assets/122351/8683449/398d7a3a-2a73-11e5-9b89-1997d89d06c2.png)

**Comment by ale-rt** [comment]
In PR #530 I implemented the menu from prototype:
1. My Profile points to http://localhost:8080/Plone/@@my-profile
2. Personal settings points to http://localhost:8080/Plone/@@my-profile#person-info (and works fine opening the right tab)
3. Logout points to http://localhost:8080/Plone/logout

The three functionalities are covered by robot tests.

IMHO we should merge #530 (once jenkins is fine with that) and close this issue, given that @@personal-preferences has been turned of by #513
