### ISSUE TITLE
workspace Participant policy Consume - user has still all add buttons and they fail

### ISSUE THREAD

**Issue by maartenkling** [ploneintranet/ploneintranet#449]

**Comment by allcaps** [comment]
The button should stay. It's a bug deep in security. Ask @gyst.
The real bug: A normal user should be able to add a workspace.

**Comment by gyst** [comment]
Sorry for the confusion. Adding a workspace is #438 - this plays out in the "workspaces" container view.

This ticket is something different: in a Consume workspace a user has no right to add content, hence should have no "add document", "add folder" buttons. Possibly already fixed in #505 please check.

**Comment by gyst** [comment]
Fixed in #508
