### ISSUE TITLE
Sidebar/members shows dummy text for user status

### ISSUE THREAD

**Issue by pilz** [ploneintranet/ploneintranet#460]
![screen shot 2015-07-09 at 13 07 37](https://cloud.githubusercontent.com/assets/138906/8593828/7f1dac46-263b-11e5-8214-a3a4c625f763.png)

The description text below the name is still dummy.

**Comment by ale-rt** [comment]
I am going to take this one.
If I am not wrong I should display there the biography of the user.

**Comment by pilz** [comment]
Hold on, I think @gyst planned to use some other data there.

**Comment by mattss** [comment]
I believe that @cornae envisaged this as a 'status' line for a user, which also appear on their user profile and in search results. However this status line has recently been ditched from the prototype.

**Comment by mattss** [comment]
To clarify - the status line has recently been ditched from the _profile_ page in the prototype

**Comment by ale-rt** [comment]
Ok, I will stop.

For future reference, to remove the dummy text we have to modify those line:
- https://github.com/ploneintranet/ploneintranet/blob/2c7cde555662e4de4494196b764f6ecbc479aa05/src/ploneintranet/workspace/workspacefolder.py#L150
- https://github.com/ploneintranet/ploneintranet/blob/e01e3975fc8378df0c5f6a2f22f86cb844f6682e/src/ploneintranet/workspace/utils.py#L91

The logic in those lines is duplicated... we should fix this.

To get the description I think we should take the property of the user called 'description'.
So those lines will become:

``` diff
index 3d7c3dc..c04c008 100644
--- a/src/ploneintranet/workspace/utils.py
+++ b/src/ploneintranet/workspace/utils.py
@@ -87,8 +87,7 @@ def existing_users(context):
             continue
         user = user.getUser()
         title = user.getProperty('fullname') or user.getId() or userid
-        # XXX tbd, we don't know what a persons description is, yet
-        description = _(u'Here we could have a nice status of this person')
+        description = user.getProperty('description')
         classes = description and 'has-description' or 'has-no-description'
         portal = api.portal.get()
         portrait = '%s/@@avatars/%s' % \
diff --git a/src/ploneintranet/workspace/workspacefolder.py b/src/ploneintranet/workspace/workspacefolder.py
index eecac0d..7a9f2fc 100644
--- a/src/ploneintranet/workspace/workspacefolder.py
+++ b/src/ploneintranet/workspace/workspacefolder.py
@@ -146,9 +146,7 @@ class WorkspaceFolder(Container):
                 continue
             user = user.getUser()
             title = user.getProperty('fullname') or user.getId() or userid
-            # XXX tbd, we don't know what a persons description is, yet
-            description = MessageFactory(u'Here we could have a nice status of'
-                                         u' this person')
+            description = user.getProperty('description')
             classes = description and 'has-description' or 'has-no-description'
             portrait = pi_api.userprofile.avatar_url(userid)
             info.append(
```

**Comment by gyst** [comment]
Certainly not a user description. I have agreement with @cornae that this should become something like "Last seen on 2015-05-19 20:00" with a pat-moment markup, both on the profile page and in the sidebar. However that has not been designed and we're now in feature freeze, so the best course with this ticket is to remove the status line now.

**Comment by cornae** [comment]
Agree. And it would indeed be that kind of status line. The markup is commented out in the markup but still supported by the CSS, so it can be re-added at will. Talking about pat-moment, @adrianwhite Did you see my question about it? I couldn't get it to work.

**Comment by adrianwhite** [comment]
@cornae Sorry I did not see your question. Could you please send me a notification from the relevant place?
I must admit I have not been reading every email that comes through from GitHub. I need to filter my emails better.

**Comment by cornae** [comment]
I think it's easier for you to find it because it should be in your mail box. Maybe if you search on pat-moment or pat-date-time. The ticket says it's pat-moment but from JC I understood it's pat-date-time. The pattern was created outside the design cycle so I cannot answer which one it should be. Either way, neither worked. 

In Slack I found:

Cornelis G. A. Kolbach [16:32] 
What is the pattern syntax for relative date?

jc [16:33] 
I didn't work on that, so not sure

jc[16:33]
https://github.com/ploneintranet/pat-display-time

GitHub
ploneintranet/pat-display-time
Contribute to pat-display-time development by creating an account on GitHub.

Cornelis G. A. Kolbach [16:33] 
Who made that?

Cornelis G. A. Kolbach[16:33]
ok

jc [16:33] 
adrian white

jc[16:34]
@adrian: ^

Cornelis G. A. Kolbach [16:34] 
so it’s called pat-display-time

Cornelis G. A. Kolbach[16:34]
hm

Cornelis G. A. Kolbach [18:10] 
I was waiting for your commit, but I see a change, you already did it?

jc [18:16] 
@cornelis: I released the javascript a few minutes ago

jc[18:16]
Did you run "make designerhappy"?

Cornelis G. A. Kolbach [18:16] 
Yes

Cornelis G. A. Kolbach[18:16]
I didn’t hear anything, so i thought i would try :simple_smile:

The ticket is by the way still open I noticed https://github.com/ploneintranet/ploneintranet.prototype/issues/46 So I had also the impression that it's not finished maybe. The bottom line is that I cannot get it to work. Can you point to a working example or put one in proto that i can replicate?
