### ISSUE TITLE
Items since 'ever'

### ISSUE THREAD

**Issue by cornae** [ploneintranet/ploneintranet#590]
In the workspace document sidebar and grouped by date, 'Items since 'ever' seems an odd way to communicate a time span. Wouldn't 'Older' look better?

![image](https://cloud.githubusercontent.com/assets/738601/8746800/2533e490-2c8d-11e5-9f5f-115dfd8710d9.png)

**Comment by ale-rt** [comment]
I agree, 'Items since 'ever' looks odd.
Anyway 'Older' is incorrect, because 'All times' gives you unfiltered items.
We could just drop the description.

Anyway, when the proper words come out, the description can be modified here:
-  https://github.com/ploneintranet/ploneintranet/blob/cda66e41ff09139b11d15ff7fe28b3fe3422edc2/src/ploneintranet/workspace/browser/tiles/sidebar.py#L623
