### ISSUE TITLE
Why are we showing roles in user picker?

### ISSUE THREAD

**Issue by pysailor** [ploneintranet/ploneintranet#63]
I'm working on getting the mentions working in the social stream.
I notice that the user-picker always shows a user's roles as description under the name:
![screen shot 2015-03-14 at 16 55 01](https://cloud.githubusercontent.com/assets/642660/6652394/273d592e-ca6d-11e4-8b36-f52b115945db.png)
I want to question the usefulness of this.

The prototype foresees a status text for this (which we don't yet support afaik):
![screen shot 2015-03-14 at 17 13 27](https://cloud.githubusercontent.com/assets/642660/6652400/801bfcda-ca6d-11e4-8a06-febb92d8e32b.png)

@gyst OK to not show a user's roles? And once we have a personal status text, show that as the description?

**Comment by cornae** [comment]
The user role was put there at the time only to demonstrate that a byline was possible. It dates back to last summer so we don't have this very fresh our minds anymore ;). I would say the role is not too relevant in this context, especially since there are no global roles. The Person's status text would in this case indeed be a good piece of content for the byline once we have that content available.

**Comment by pysailor** [comment]
Ok, I will remove showing the user's (global!) roles, as they give no value. Instead I will foresee that the user's "status" is shown, knowing that currently we don't have one. So the user picker will look like this:

![screen shot 2015-03-17 at 21 41 50](https://cloud.githubusercontent.com/assets/642660/6697097/890a75e6-ccee-11e4-9347-d2d585d9458a.png)

**Comment by cornae** [comment]
Perfect.

**Comment by gyst** [comment]
fixed in 47cf67b
