### ISSUE TITLE
solr jenkins fixes

### ISSUE THREAD

**Issue by gyst** [ploneintranet/ploneintranet#692]

**Comment by mattss** [comment]
Still investigating this - the issue is not specifically solr related, but a weird test conflict related to the order things are installed (my favourite). The error was introduced by the changes from https://github.com/ploneintranet/ploneintranet/issues/451 which introduce a new behaviour and model for the default file and image types. 

@cillianderoiste can you shed any light on the changes in #451? Can't find any tests that explain why we are adding a new file field, which makes it hard for me to work out exactly what's wrong here.

**Comment by mattss** [comment]
Work ongoing here: https://github.com/ploneintranet/ploneintranet/compare/fix-primary-fields

I've added some tests to try and and verify that the p.a.contenttypes overrides are actually being applied.

**Comment by mattss** [comment]
What _appears_ to be happening in the solr stack, is that the model overrides from p.i.workspace are being applied (which removes the default file field), but the behaviour is not, so we end up with no primary field on the type.

**Comment by cillianderoiste** [comment]
Does #626 provide a better explanation?

**Comment by mattss** [comment]
@cillianderoiste ah yes that's clearer, thanks.
