### ISSUE TITLE
Proposal to list all users when no search term is given by default

### ISSUE THREAD

**Issue by pilz** [ploneintranet/ploneintranet#755]
A quick solution to our problem that the profile folder has no proper view could be to show the people_search form. But then it should list users by default. It already does batching - showing only 15 users by default - and would be a great entry point for searching more. The only change required would be not to abort if there are no search keywords. 

@mattss, @gyst: Does that make sense?

**Comment by gyst** [comment]
In general I'm +1 for not hard-requiring SearchableText in search, as long as another parameter is  searched for. IIRC that has already been changed in the search backend API as part of the library tag views work.

As to your specific proposal I'm on the fence. What problem exactly does this solve - we don't expose the profiles folder, do we?

## 

   Guido Stevens  |  +31.43.3618933  |  http://cosent.nl

   s o c i a l   k n o w l e d g e   t e c h n o l o g y

**Comment by pilz** [comment]
If you go on a user profile, you can click the profiles folder in the what-used-to-be-the breadcrumbs. It shows an ugly folder contents listing.

**Comment by gyst** [comment]
OK. So you want to re-use people search, without the other search tabs, and with the extra behavior of immediately listing everybody (batched). OK.

Note that it may be cheaper to redirect to people search.

## 

   Guido Stevens  |  +31.43.3618933  |  http://cosent.nl

   s o c i a l   k n o w l e d g e   t e c h n o l o g y

**Comment by pilz** [comment]
I want to redirect to people search. I just need it to already show something. Redirecting to an empty search result page is demotivating and confusing :)

**Comment by gyst** [comment]
Let's take this up with Cornelis. I don't like changing the default behavior of people search, since that would not be consistent with the other searches which start empty. I also dislike switching ?browse=1 (showing initial results only from the profiles folder) since that makes people search (from profiles) inconsistent with people search (from search).

A solution may be to show "your top 10 collaborators" as placeholder to overcome the empty screen syndrome. But that may detract from the search experience and be confusing.

## @cornae your input on this thread please?

   Guido Stevens  |  +31.43.3618933  |  http://cosent.nl

   s o c i a l   k n o w l e d g e   t e c h n o l o g y

**Comment by cornae** [comment]
I'm clicking through my designs looking for anything you might refer to as 'user folder', but I have no clue what that should be so I also can't place the question. Can you help me out what this is?

**Comment by mattss** [comment]
Probably worth noting here that in the software, profiles exist inside a specific containing folder (because that makes them easier to manage), so profile URLs are of the form:

/site/profiles/username

whereas the prototype has no such concept of this container, and urls are of the form:

/site/username

**Comment by cornae** [comment]
Ok, Thanks, that clears it up a bit. I think it's simple then, since there is no design, there is also no page to be built and 'profiles' does not need to appear in the breadcrumbs (Although I think it's not a bad idea to have that word there) or not to be linked.

**Comment by pilz** [comment]
The simplest and most straightforward solution :)

> Am 07.09.2015 um 18:21 schrieb Cornelis G. A. Kolbach notifications@github.com:
> 
> Ok, Thanks, that clears it up a bit. I think it's simple then, since there is no design, there is also no page to be built and 'profiles' does not need to appear in the breadcrumbs (Although I think it's not a bad idea to have that word there) or not to be linked.
> 
> —
> Reply to this email directly or view it on GitHub https://github.com/ploneintranet/ploneintranet/issues/755#issuecomment-138334991.

## 

Alexander Pilz
SYSLAB.COM GmbH, Landwehrstrasse 60-62, 80336 Munich, Germany
Tel: +49 89 3063589-0 - Fax: +49 89 3063589-9
http://www.syslab.com - Amtsgericht Muenchen, HRB 135057
Steuernummer 143/184/50154 - Ust.-ID: DE212842815
