### ISSUE TITLE
Case sensitivity in tags

### ISSUE THREAD

**Issue by bfackland** [ploneintranet/ploneintranet#858]
At the moment you can have two different tags on the same document that are the same word but in a different mix of cases:

![screen shot 2015-10-22 at 16 45 34](https://cloud.githubusercontent.com/assets/2538526/10670239/87ad73b6-78dc-11e5-8072-6c66285ee276.png)

It appears that they are normalised when they are indexed and searched, which is good.

@gyst Was it a deliberate design decision to allow tags to be entered (and auto-completed in the process) in different cases? My general understanding of tagging is that it should be completed case insensitive. Although I can think of instances where I might want to refer to _Apple_ and _apple_ and mean different things :)

**Comment by gyst** [comment]
Case normalization has only recently been added to the stack by Wolfgang
and me.

Basically our strategy is to search case-insensitive (and utf-8
equivalent) when presenting matching tag suggestions.

So if the system has an existing tag "Börse", and you start typing "bo"
it will show that tag. If you then instead of picking this selection,
proceed to input "boerse" well you can.

In other word tag variations which only are different in casing can only
occur because of a deliberate user choice.

Forcing everything to lowercase would be awkward, especially in case

## sensitive languages like German.

```
Guido Stevens  |  +31.43.3618933  |  http://cosent.nl

s o c i a l   k n o w l e d g e   t e c h n o l o g y
```

**Comment by bfackland** [comment]
That sounds great. I concur that lowercase-only tagging won't work. Closing issue.
