### ISSUE TITLE
Failed to abort resource manager: collective.indexing.transactions.QueueTM object 

### ISSUE THREAD

**Issue by vito80ba** [ploneintranet/ploneintranet#894]
Hi all,
I follow the instructions on doc.ploneintranet.org to install (without docker) a fresh new buildout (in a virtual env) to explore ploneintranet.
Bin/buildout is ok and Redis also.
I run the instance without any problem but when I choose to create a new plone instance I obtain:
ERROR txn.4633784320 Failed to abort resource manager: collective.indexing.transactions.QueueTM object at 0x112043b48

Complete traceback : http://pastie.org/10685075 
Mac OS "Mountain Lion"

I made the same on my macbook ("El Captain") with success.

Have you any idea to solve this problem?
Thank's

**Comment by ckirchhoff** [comment]
Hi Vito,

do you see other errors further up? Anyway, I got the same error and it turned out to be because I had not installed tkinter. 'apt-get install python-tk' solved the problem on Ubuntu, you should try the equivalent on your Mac. Apparently tkinter should be added to the list of dependencies.

cheers
Claudio

**Comment by vito80ba** [comment]
Yes, you're right
it seems to be a bug on Mac regarding Tk
http://bugs.python.org/issue19373

Maybe it's time to use Vagrant for me ;)
